// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma-next contract emit'.
// To regenerate, run: prisma-next contract emit
import type { CodecTypes as PgTypes } from '@prisma-next/target-postgres/codec-types';
import type { JsonValue } from '@prisma-next/target-postgres/codec-types';
import type { Char } from '@prisma-next/target-postgres/codec-types';
import type { Varchar } from '@prisma-next/target-postgres/codec-types';
import type { Numeric } from '@prisma-next/target-postgres/codec-types';
import type { Bit } from '@prisma-next/target-postgres/codec-types';
import type { VarBit } from '@prisma-next/target-postgres/codec-types';
import type { Timestamp } from '@prisma-next/target-postgres/codec-types';
import type { Timestamptz } from '@prisma-next/target-postgres/codec-types';
import type { Time } from '@prisma-next/target-postgres/codec-types';
import type { Timetz } from '@prisma-next/target-postgres/codec-types';
import type { Interval } from '@prisma-next/target-postgres/codec-types';
import type { QueryOperationTypes as PgAdapterQueryOps } from '@prisma-next/adapter-postgres/operation-types';

import type {
  ContractWithTypeMaps,
  TypeMaps as TypeMapsType,
} from '@prisma-next/sql-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma-next/contract/types';

export type StorageHash =
  StorageHashBase<'sha256:1fc3d7b399a31953ca13f5fa8590e5dee01f7b7645c61ad03dbcd98942092292'>;
export type ExecutionHash =
  ExecutionHashBase<'sha256:0e9f54d1996ac6994a949c12bdbef63249d19b200b4038222027d18950809955'>;
export type ProfileHash =
  ProfileHashBase<'sha256:1a8dbe044289f30a1de958fe800cc5a8378b285d2e126a8c44b58864bac2c18e'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes>;
type DefaultLiteralValue<CodecId extends string, _Encoded> = CodecId extends keyof CodecTypes
  ? CodecTypes[CodecId]['output']
  : _Encoded;

export type FieldOutputTypes = {
  readonly ClickerDevice: {
    readonly id: Char<36>;
    readonly name: CodecTypes['pg/text@1']['output'];
    readonly location: CodecTypes['pg/text@1']['output'] | null;
    readonly createdAt: CodecTypes['pg/timestamptz@1']['output'];
    readonly updatedAt: CodecTypes['pg/timestamptz@1']['output'];
  };
  readonly VisitorEvent: {
    readonly id: Char<36>;
    readonly deviceId: CodecTypes['pg/text@1']['output'];
    readonly direction: CodecTypes['pg/text@1']['output'];
    readonly count: CodecTypes['pg/int4@1']['output'];
    readonly occurredAt: CodecTypes['pg/timestamptz@1']['output'];
    readonly createdAt: CodecTypes['pg/timestamptz@1']['output'];
  };
};
export type FieldInputTypes = {
  readonly ClickerDevice: {
    readonly id: CodecTypes['sql/char@1']['input'];
    readonly name: CodecTypes['pg/text@1']['input'];
    readonly location: CodecTypes['pg/text@1']['input'] | null;
    readonly createdAt: CodecTypes['pg/timestamptz@1']['input'];
    readonly updatedAt: CodecTypes['pg/timestamptz@1']['input'];
  };
  readonly VisitorEvent: {
    readonly id: CodecTypes['sql/char@1']['input'];
    readonly deviceId: CodecTypes['pg/text@1']['input'];
    readonly direction: CodecTypes['pg/text@1']['input'];
    readonly count: CodecTypes['pg/int4@1']['input'];
    readonly occurredAt: CodecTypes['pg/timestamptz@1']['input'];
    readonly createdAt: CodecTypes['pg/timestamptz@1']['input'];
  };
};
export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes
>;

type ContractBase = ContractType<
  {
    readonly namespaces: {
      readonly __unbound__: {
        readonly id: '__unbound__';
        readonly kind: 'sql-namespace';
        readonly tables: {
          readonly clickerDevice: {
            columns: {
              readonly id: {
                readonly nativeType: 'character';
                readonly codecId: 'sql/char@1';
                readonly nullable: false;
                readonly typeParams: { readonly length: 36 };
              };
              readonly name: {
                readonly nativeType: 'text';
                readonly codecId: 'pg/text@1';
                readonly nullable: false;
              };
              readonly location: {
                readonly nativeType: 'text';
                readonly codecId: 'pg/text@1';
                readonly nullable: true;
              };
              readonly createdAt: {
                readonly nativeType: 'timestamptz';
                readonly codecId: 'pg/timestamptz@1';
                readonly nullable: false;
                readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
              };
              readonly updatedAt: {
                readonly nativeType: 'timestamptz';
                readonly codecId: 'pg/timestamptz@1';
                readonly nullable: false;
              };
            };
            primaryKey: { readonly columns: readonly ['id'] };
            uniques: readonly [];
            indexes: readonly [];
            foreignKeys: readonly [];
          };
          readonly visitorEvent: {
            columns: {
              readonly id: {
                readonly nativeType: 'character';
                readonly codecId: 'sql/char@1';
                readonly nullable: false;
                readonly typeParams: { readonly length: 36 };
              };
              readonly deviceId: {
                readonly nativeType: 'text';
                readonly codecId: 'pg/text@1';
                readonly nullable: false;
              };
              readonly direction: {
                readonly nativeType: 'text';
                readonly codecId: 'pg/text@1';
                readonly nullable: false;
              };
              readonly count: {
                readonly nativeType: 'int4';
                readonly codecId: 'pg/int4@1';
                readonly nullable: false;
                readonly default: {
                  readonly kind: 'literal';
                  readonly value: DefaultLiteralValue<'pg/int4@1', 1>;
                };
              };
              readonly occurredAt: {
                readonly nativeType: 'timestamptz';
                readonly codecId: 'pg/timestamptz@1';
                readonly nullable: false;
                readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
              };
              readonly createdAt: {
                readonly nativeType: 'timestamptz';
                readonly codecId: 'pg/timestamptz@1';
                readonly nullable: false;
                readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
              };
            };
            primaryKey: { readonly columns: readonly ['id'] };
            uniques: readonly [];
            indexes: readonly [];
            foreignKeys: readonly [
              {
                readonly source: {
                  readonly namespaceId: '__unbound__';
                  readonly tableName: 'visitorEvent';
                  readonly columns: readonly ['deviceId'];
                };
                readonly target: {
                  readonly namespaceId: '__unbound__';
                  readonly tableName: 'clickerDevice';
                  readonly columns: readonly ['id'];
                };
                readonly constraint: true;
                readonly index: true;
              },
            ];
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  },
  {
    readonly ClickerDevice: {
      readonly fields: {
        readonly id: {
          readonly nullable: false;
          readonly type: {
            readonly kind: 'scalar';
            readonly codecId: 'sql/char@1';
            readonly typeParams: { readonly length: 36 };
          };
        };
        readonly name: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
        };
        readonly location: {
          readonly nullable: true;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
        };
        readonly createdAt: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/timestamptz@1' };
        };
        readonly updatedAt: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/timestamptz@1' };
        };
      };
      readonly relations: {
        readonly events: {
          readonly to: 'VisitorEvent';
          readonly cardinality: '1:N';
          readonly on: {
            readonly localFields: readonly ['id'];
            readonly targetFields: readonly ['deviceId'];
          };
        };
      };
      readonly storage: {
        readonly table: 'clickerDevice';
        readonly fields: {
          readonly id: { readonly column: 'id' };
          readonly name: { readonly column: 'name' };
          readonly location: { readonly column: 'location' };
          readonly createdAt: { readonly column: 'createdAt' };
          readonly updatedAt: { readonly column: 'updatedAt' };
        };
      };
    };
    readonly VisitorEvent: {
      readonly fields: {
        readonly id: {
          readonly nullable: false;
          readonly type: {
            readonly kind: 'scalar';
            readonly codecId: 'sql/char@1';
            readonly typeParams: { readonly length: 36 };
          };
        };
        readonly deviceId: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
        };
        readonly direction: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
        };
        readonly count: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
        };
        readonly occurredAt: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/timestamptz@1' };
        };
        readonly createdAt: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/timestamptz@1' };
        };
      };
      readonly relations: {
        readonly device: {
          readonly to: 'ClickerDevice';
          readonly cardinality: 'N:1';
          readonly on: {
            readonly localFields: readonly ['deviceId'];
            readonly targetFields: readonly ['id'];
          };
        };
      };
      readonly storage: {
        readonly table: 'visitorEvent';
        readonly fields: {
          readonly id: { readonly column: 'id' };
          readonly deviceId: { readonly column: 'deviceId' };
          readonly direction: { readonly column: 'direction' };
          readonly count: { readonly column: 'count' };
          readonly occurredAt: { readonly column: 'occurredAt' };
          readonly createdAt: { readonly column: 'createdAt' };
        };
      };
    };
  }
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly clickerDevice: 'ClickerDevice';
    readonly visitorEvent: 'VisitorEvent';
  };
  readonly capabilities: {
    readonly postgres: {
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly returning: true;
    };
  };
  readonly extensionPacks: {};
  readonly execution: {
    readonly executionHash: ExecutionHash;
    readonly mutations: {
      readonly defaults: readonly [
        {
          readonly ref: { readonly table: 'clickerDevice'; readonly column: 'id' };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: { readonly table: 'clickerDevice'; readonly column: 'updatedAt' };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
          readonly onUpdate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
        },
        {
          readonly ref: { readonly table: 'visitorEvent'; readonly column: 'id' };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
      ];
    };
  };
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
export type Models = Contract['models'];
